PACKAGE=freedoko

# Edited for Debian GNU/Linux.
DESTDIR = 


.PHONY: all
all :

.PHONY: install
install :
	mkdir -p $(DESTDIR)/usr/share/doc/$(PACKAGE)
	cp AUTHORS copyright $(DESTDIR)/usr/share/doc/$(PACKAGE)/
	echo "For more documentation look at the documentation of the package 'freedoko-binary'" \
	  > $(DESTDIR)/usr/share/doc/$(PACKAGE)/README
