PACKAGE=freedoko-manual-en
include Makefile.install.directories

# Edited for Debian GNU/Linux.
DESTDIR = 

.PHONY: all
all :

.PHONY: install
install :
	mkdir -p $(DESTDIR)/usr/share/doc/$(PACKAGE)/
	cp AUTHORS copyright $(DESTDIR)/usr/share/doc/$(PACKAGE)/
	mkdir -p $(DESTDIR)/$(HELP_DIRECTORY)/manual
	cp -a ./doc/manual/en $(DESTDIR)/$(HELP_DIRECTORY)/manual/en
